@echo off

rem download CUE4Parse.CLI here: https://github.com/joric/CUE4Parse.CLI
rem missing_files.txt is generated by build_markers.py (you need WorldMap_WP.json first)

set exe=CUE4Parse.CLI.exe
set out=C:\Temp\Exports
set gamePath=E:\Games\S.T.A.L.K.E.R. 2.Heart.of.Chornobyl.Ultimate.Editon-InsaneRamZes\
set mappings="%gamePath%\Stalker2.usmap"
set paks="%gamePath%\Stalker2\Content\Paks"
set options=-d %paks% -m %mappings% -g GAME_UE5_1 -o %out% -e

%exe% %options% -i %~dp0\assetlist.txt

if exist %~dp0\missing_files.txt (
	%exe% %options% -i %~dp0\missing_files.txt
)
