@echo off

rem download CUE4Parse.CLI here: https://github.com/joric/CUE4Parse.CLI

for /f "usebackq delims=" %%a in (".env") do set %%a

set exe=cue4parse

set options=-i "%GAME_DIR%" -m "%MAPPINGS_FILE%" -g GAME_UE5_5 -o %EXPORT_DIR%

%exe% %options% -c assetlist.txt || exit

rem missing_files.txt is generated by build_markers.py (you need WorldMap_WP.json first)

if exist missing_files.txt (
    %exe% %options% -c missing_files.txt
)

if exist missing_icons.txt (
    %exe% %options% -c missing_icons.txt
)
